name: Train Model

on:
  workflow_dispatch:

jobs:
  train-model:
    name: Train custom model
    timeout-minutes: 2880
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --unset http.https://github.com/.extraheader
          git config user.name daavoo
          git config user.email daviddelaiglesiacastro@gmail.com
          git remote set-url origin https://daavoo:$REPO_TOKEN@github.com/daavoo/debug-missing-metrics.git

      - run: pip install dvc dvclive

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}
          DVCLIVE_LOGLEVEL: INFO
        run: dvc exp run model_training/dvc.yaml
      - run: dvc exp push origin
